# Generated by Django 4.2 on 2023-05-02 19:10


from django.db import migrations


def load_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")

    role_superadmin = Role(id=1, name='IS_SUPERADMIN')
    role_superadmin.save()

    role_admin = Role(id=2, name='IS_ADMIN')
    role_admin.save()

    is_client = Role(id=3, name='IS_CLIENT')
    is_client.save()


def delete_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_roles, delete_roles),
    ]
